name: CI security linting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]
    paths:
      - '.github/**'

permissions: {}

jobs:
  zizmor:
    name: zizmor latest via Cargo
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false
      - name: Install zizmor
        run: cargo install --locked zizmor
      - name: Run zizmor
        run: zizmor .github/workflows
